### ISSUE TITLE
Copy tables?

### ISSUE THREAD

**Issue by iamgp** [ryangjchandler/alpine-clipboard#13]
Hi Ryan,

Great plugin!

Quick question/feature request - is there a way to copy table data? For example, I'd like to copy the table generated in the following:

```html
<p @click="$clipboard(?)">Copy the below table and paste it somewhere/p>
<table class="table-auto">
    <template x-for="example in examples" :key="example.ID">
        <tr>
            <td x-html="example.attr1"></td>
            <td x-html="example.attr2"></td>
        </tr>
    </template>
</table>
```

Cheers :)

**Comment by ryangjchandler** [comment]
@iamgp That's not something that I've tried, personally. Would you want to copy the actual markup of the table?

**Comment by iamgp** [comment]
@ryangjchandler, sorry for the delay Ryan. Essentially I'd like to be able to copy a table and be able to paste it into Excel/Google Sheets etc. Markup isn't necessary, in most cases I think only the text would be copied. Thanks for taking a look into this and thank you for everything you do for alpine.

**Comment by rehhouari** [comment]
> @iamgp Best way is to make a function that convert the table's data to a csv string, then either:
> - simply copy the csv string, users can paste that in sheets but it isn't straightforward.
> - [save/download the csv as a file](https://jsfiddle.net/gengns/j1jm2tjx/) which can be opened with Sheets or Excel directly.
