### ISSUE TITLE
Livewire support without `wire:model`

### ISSUE THREAD

**Issue by ju5t** [ryangjchandler/alpine-clipboard#18]
To be honest I'm not sure if this is the right place, so feel free to close this issue if needed. A pointer where to post this would be appreciated if this is the wrong place :)

I'm using the `$clipboard` in an app that I am still building. This uses Livewire for a lot of things. In this specific case I have a list of users with a button to create or edit users. This opens up a modal. When the user is saved it emits a signal for other components to pick up. In this case, I'm just refreshing the list of users, that contains a few `$clipboard`'s.

The `$clipboard`'s aren't refreshed.

I don't really want to wire things up as it's not supposed to be two-way data (the list does not contain inputs).

I hope someone here might know a solution

**Comment by ryangjchandler** [comment]
@ju5t Is the DOM not being updated at all?

**Comment by ju5t** [comment]
@ryangjchandler it is, I verified with Ray too and added `now()` to the list. When I remove the clipboard and just use standard blade to output the user's name for example, it refreshes as expected.

I'm pretty sure this is not related to `$clipboard` right now as this code, doesn't refresh either:

```blade
<span x-data="{ value: '{{ $user->name }}' }">
    <span x-html="value" />
</span>
```

`$user` is inside the loop, by the way. It's too bad it doesn't work as this is a pretty useful thing for us. I'll ask at Livewire.

**Comment by ryangjchandler** [comment]
I'd maybe try a `wire:key` as well.

**Comment by ju5t** [comment]
I initially typed a lot more in my previous reply. TLDR-version; I tried `wire:key` and using custom id's combined with `{{ $loop>index }}` but that made no difference, unfortunately.

**Comment by ryangjchandler** [comment]
Yeah, this is a problem even without `$clipboard` based on my own reproduction cases.

**Comment by ju5t** [comment]
I've opened up https://github.com/livewire/livewire/discussions/3778 to continue this. I don't think this issue should stay open so I will close it.
