### ISSUE TITLE
Doesn't work on the mobile version of safari

### ISSUE THREAD

**Issue by jet10000** [ryangjchandler/alpine-clipboard#20]
# ios 14.8.1

```
npx esbuild main.js --outfile=../dist/js/bundle.js --bundle --watch
```

```
import Clipboard from "@ryangjchandler/alpine-clipboard"

Alpine.plugin(Clipboard)

window.Alpine = Alpine;

Alpine.start()
```

```
        <p>
            <button type="button" @click="$clipboard(res)" class="btn-pink">Copy</button>
        </p>
```

**Comment by ryangjchandler** [comment]
According to caniuse, it should work fine: https://caniuse.com/mdn-api_clipboard_writetext

**Comment by jet10000** [comment]
I found the problem, Mobile phone debugging requires https, for example: https://192.168.1.108

https://segmentfault.com/q/1010000019566122

**Comment by ryangjchandler** [comment]
@jet10000 Yeah, that's a requirement. HTTPs or `localhost` domains are required.
