### ISSUE TITLE
Package

### ISSUE THREAD

**Issue by austriker27** [ryangjchandler/alpine-clipboard#3]
As I mentioned to you, I'd love to see this packaged up so it can be installed via yarn or npm. (I know there's a CDN link but packages are preferable for me).

Thanks good sir!

**Comment by ryangjchandler** [comment]
Hey @austriker27! Turns out I've been publishing the package to NPM already, I just didn't document it in the README:
https://www.npmjs.com/package/@ryangjchandler/alpine-clipboard

I'll close this issue when I update the docs some point this week. Thanks for pointing this out!
