### ISSUE TITLE
Multiline text not copying

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/alpine-clipboard#8]

**Comment by spekulatius** [comment]
Hey @ryangjchandler 

I just stumbled upon the multi line issue:

![image](https://user-images.githubusercontent.com/8433587/112715939-dd432500-8efc-11eb-9194-9e82b662d6b2.png)

Any ideas on how you would address this?

Cheers,
Peter

**Comment by ryangjchandler** [comment]
Hi @spekulatius - I'll try to get this reproduce in a CodePen.

**Comment by spekulatius** [comment]
Thanks, let me know if you got any questions!
